version: '2'

services:

  elasticsearch:
    build: docker-elk/elasticsearch/
    volumes:
      - ./docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      logger.level: warn
    networks:
      - elk

  kibana:
    build: docker-elk/kibana/
    volumes:
      - ./docker-elk/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  node:
    env_file: .env
    environment:
      ELASTICSEARCH_HOST: "elasticsearch:9200"
    build: ./
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:

  elk:
    driver: bridge
